### ISSUE TITLE
Please confirm the I've done this correctly

### ISSUE THREAD

**Issue by morio** [rabbitholecomputing/CUEParser#1]
I've added a README.md and license files along with github workflow for running the tests. Please check that everything is good and there are no typos.

**Comment by PetteriAimonen** [comment]
I think it would be better to bring in the repo history with `git-filter-repo`.

I don't have permissions to force push to this repo, but attached is a zip with full history included.
[CUEParser.zip](https://github.com/user-attachments/files/17239647/CUEParser.zip)

**Comment by aperezbios** [comment]
Agreed. @morio can you make this happen? Mahalo!

**Comment by morio** [comment]
> I think it would be better to bring in the repo history with `git-filter-repo`.
> 
> I don't have permissions to force push to this repo, but attached is a zip with full history included. [CUEParser.zip](https://github.com/user-attachments/files/17239647/CUEParser.zip)

I've forced push the repo up and respun the release with the new commit ID
